pragma solidity ^0.5.17;

contract EscrowTrustedPaymentV1 {
   address requestorAddress; // the one who requested a job to be made
   address workerAddress;    // the one who is working on the job
   address escrow;           // the one who verifies whether the worker has completed the task or not in case of a dispute between the two
   
   uint escrowThreshodl;     // how many of the escrow addesses that must accept or decline a dispute

   // TODO: ADD DATA FIELDS AND FUNCTIONS FOR:
   // 
   // 1) 64 BYTE PUBLIC KEY FOR THE WORK DESCRIPTON, UPLOADED BY THE REQUESTOR, WHICH LEADS TO:
   //    1.1) JSON-FORMATTED DESCRIPTION OF, FOR EXAMPLE, BROADCASTED MESSAGES (CHAT); THE WORK; WHAT THE WORKER MUST DO; HOW THE ESCROW CAN VERIFY; WITHIN WHICH TIMEFRAME THE WORKER MUST COMPLETE THE TASK; PART-DELIVERABLES; ETC
   //    1.2) (OPTIONAL) REQUIRED ENVIRONMENT FILES
   //    1.3) (OPTIONAL) HIGHLY TECHNICAL & DETAILED DESCRIPTION OF THE JOB
   //    (1.(4-∞) ADDITIONAL FILES)
   // 
   // 2) 64 BYTE PUBLIC KEY FOR THE WORKER'S WORK FILES, UPLOADED BY THE WORKER, WHICH LEADS TO:
   //    2.1) JSON-FORMATTED MESSAGE/DETAILS REGARDING THE JOB (E.G. HOW COMPLETE IT IS (INCL. MENTIONING THAT THE WORK IS DONE AND THAT THEY WANT TO GET PAID OUT), ANY QUESTIONS, ETC)
   //    2.2) WORK FILES

   constructor() public{
      requestorAddress = 0x0000000000000000000000000000000000000000;
      workerAddress = 0x0000000000000000000000000000000000000000;
      escrow = 0x0000000000000000000000000000000000000000;
   }
   
   // TODO: MAKE FUNCTION THAT LETS THE REQUESTOR CHANGE ESCROW FOR AS LONG AS THERE IS ONLY A DEFAULT VALUE FOR THE WORKER ADDRESS

   // TODO: MAKE FUNCTION THAT LETS THE REQUESTOR CHANGE THE WORK DESCRIPTION FOR AS LONG AS THERE IS ONLY A DEFAULT VALUE FOR THE WORKER ADDRESS

   // TODO: MAKE FUNCTION THAT LETS THE WORKER START A DISPUTE, I.E., ASKING ESCROW TO OVERLOOK THE FINISHED WORK BY CHANGING A STATE BOOL

   // TODO: MAKE FUNCTION THAT LETS THE REQUESTOR START A DISPUTE, I.E., ASKING ESCROW TO GIVE BACK THE REQUESTORS' FUNDS BY CHANGING A STATE BOOL

   // TODO: MAKE FUNCTION THAT LETS ESCROW PAY THE WORKER / REQUESTOR BASED ON DISPUTES

   // TODO: MAKES FUNCTION THAT LETS THE REQUESTOR PAY OUT THE WORKER FROM THE CONTRACT'S FUNDS
}